/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as DocumentDocumentIdRouteImport } from './routes/document.$documentId'
import { Route as LabEmbeddingRouteImport } from './routes/lab.embedding'
import { Route as RecentDocumentsRouteImport } from './routes/recent.documents'
import { Route as RecentSentencesRouteImport } from './routes/recent.sentences'
import { Route as RecentWordsRouteImport } from './routes/recent.words'
import { Route as RelationRelationIdRouteImport } from './routes/relation.$relationId'
import { Route as RelationNewRouteImport } from './routes/relation.new'
import { Route as RelationsW2wRouteImport } from './routes/relations.w2w'
import { Route as SentenceSentenceIdRouteImport } from './routes/sentence.$sentenceId'
import { Route as WordWordRouteImport } from './routes/word.$word'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentDocumentIdRoute = DocumentDocumentIdRouteImport.update({
  id: '/document/$documentId',
  path: '/document/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabEmbeddingRoute = LabEmbeddingRouteImport.update({
  id: '/lab/embedding',
  path: '/lab/embedding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentDocumentsRoute = RecentDocumentsRouteImport.update({
  id: '/recent/documents',
  path: '/recent/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentSentencesRoute = RecentSentencesRouteImport.update({
  id: '/recent/sentences',
  path: '/recent/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWordsRoute = RecentWordsRouteImport.update({
  id: '/recent/words',
  path: '/recent/words',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationRelationIdRoute = RelationRelationIdRouteImport.update({
  id: '/relation/$relationId',
  path: '/relation/$relationId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationNewRoute = RelationNewRouteImport.update({
  id: '/relation/new',
  path: '/relation/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsW2wRoute = RelationsW2wRouteImport.update({
  id: '/relations/w2w',
  path: '/relations/w2w',
  getParentRoute: () => rootRouteImport,
} as any)
const SentenceSentenceIdRoute = SentenceSentenceIdRouteImport.update({
  id: '/sentence/$sentenceId',
  path: '/sentence/$sentenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WordWordRoute = WordWordRouteImport.update({
  id: '/word/$word',
  path: '/word/$word',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/$relationId': typeof RelationRelationIdRoute
  '/relation/new': typeof RelationNewRoute
  '/relations/w2w': typeof RelationsW2wRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/$relationId': typeof RelationRelationIdRoute
  '/relation/new': typeof RelationNewRoute
  '/relations/w2w': typeof RelationsW2wRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/$relationId': typeof RelationRelationIdRoute
  '/relation/new': typeof RelationNewRoute
  '/relations/w2w': typeof RelationsW2wRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/settings'
    | '/tools'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/$relationId'
    | '/relation/new'
    | '/relations/w2w'
    | '/sentence/$sentenceId'
    | '/word/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/settings'
    | '/tools'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/$relationId'
    | '/relation/new'
    | '/relations/w2w'
    | '/sentence/$sentenceId'
    | '/word/$word'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/settings'
    | '/tools'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/$relationId'
    | '/relation/new'
    | '/relations/w2w'
    | '/sentence/$sentenceId'
    | '/word/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  DocumentDocumentIdRoute: typeof DocumentDocumentIdRoute
  LabEmbeddingRoute: typeof LabEmbeddingRoute
  RecentDocumentsRoute: typeof RecentDocumentsRoute
  RecentSentencesRoute: typeof RecentSentencesRoute
  RecentWordsRoute: typeof RecentWordsRoute
  RelationRelationIdRoute: typeof RelationRelationIdRoute
  RelationNewRoute: typeof RelationNewRoute
  RelationsW2wRoute: typeof RelationsW2wRoute
  SentenceSentenceIdRoute: typeof SentenceSentenceIdRoute
  WordWordRoute: typeof WordWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$documentId': {
      id: '/document/$documentId'
      path: '/document/$documentId'
      fullPath: '/document/$documentId'
      preLoaderRoute: typeof DocumentDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/embedding': {
      id: '/lab/embedding'
      path: '/lab/embedding'
      fullPath: '/lab/embedding'
      preLoaderRoute: typeof LabEmbeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/documents': {
      id: '/recent/documents'
      path: '/recent/documents'
      fullPath: '/recent/documents'
      preLoaderRoute: typeof RecentDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/sentences': {
      id: '/recent/sentences'
      path: '/recent/sentences'
      fullPath: '/recent/sentences'
      preLoaderRoute: typeof RecentSentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/words': {
      id: '/recent/words'
      path: '/recent/words'
      fullPath: '/recent/words'
      preLoaderRoute: typeof RecentWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relation/$relationId': {
      id: '/relation/$relationId'
      path: '/relation/$relationId'
      fullPath: '/relation/$relationId'
      preLoaderRoute: typeof RelationRelationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relation/new': {
      id: '/relation/new'
      path: '/relation/new'
      fullPath: '/relation/new'
      preLoaderRoute: typeof RelationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/w2w': {
      id: '/relations/w2w'
      path: '/relations/w2w'
      fullPath: '/relations/w2w'
      preLoaderRoute: typeof RelationsW2wRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentence/$sentenceId': {
      id: '/sentence/$sentenceId'
      path: '/sentence/$sentenceId'
      fullPath: '/sentence/$sentenceId'
      preLoaderRoute: typeof SentenceSentenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word/$word': {
      id: '/word/$word'
      path: '/word/$word'
      fullPath: '/word/$word'
      preLoaderRoute: typeof WordWordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  DocumentDocumentIdRoute: DocumentDocumentIdRoute,
  LabEmbeddingRoute: LabEmbeddingRoute,
  RecentDocumentsRoute: RecentDocumentsRoute,
  RecentSentencesRoute: RecentSentencesRoute,
  RecentWordsRoute: RecentWordsRoute,
  RelationRelationIdRoute: RelationRelationIdRoute,
  RelationNewRoute: RelationNewRoute,
  RelationsW2wRoute: RelationsW2wRoute,
  SentenceSentenceIdRoute: SentenceSentenceIdRoute,
  WordWordRoute: WordWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
