 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as QnaRouteImport } from './routes/qna'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocumentDocumentIdRouteImport } from './routes/document.$documentId'
import { Route as LabEmbeddingRouteImport } from './routes/lab.embedding'
import { Route as RecentDocumentsRouteImport } from './routes/recent.documents'
import { Route as RecentSentencesRouteImport } from './routes/recent.sentences'
import { Route as RecentWordsRouteImport } from './routes/recent.words'
import { Route as RelationNewRouteImport } from './routes/relation.new'
import { Route as SentenceSentenceIdRouteImport } from './routes/sentence.$sentenceId'
import { Route as WordWordRouteImport } from './routes/word.$word'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const QnaRoute = QnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentDocumentIdRoute = DocumentDocumentIdRouteImport.update({
  id: '/document/$documentId',
  path: '/document/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabEmbeddingRoute = LabEmbeddingRouteImport.update({
  id: '/lab/embedding',
  path: '/lab/embedding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentDocumentsRoute = RecentDocumentsRouteImport.update({
  id: '/recent/documents',
  path: '/recent/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentSentencesRoute = RecentSentencesRouteImport.update({
  id: '/recent/sentences',
  path: '/recent/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWordsRoute = RecentWordsRouteImport.update({
  id: '/recent/words',
  path: '/recent/words',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationNewRoute = RelationNewRouteImport.update({
  id: '/relation/new',
  path: '/relation/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SentenceSentenceIdRoute = SentenceSentenceIdRouteImport.update({
  id: '/sentence/$sentenceId',
  path: '/sentence/$sentenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WordWordRoute = WordWordRouteImport.update({
  id: '/word/$word',
  path: '/word/$word',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/qna': typeof QnaRoute
  '/settings': typeof SettingsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/new': typeof RelationNewRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/qna': typeof QnaRoute
  '/settings': typeof SettingsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/new': typeof RelationNewRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/qna': typeof QnaRoute
  '/settings': typeof SettingsRoute
  '/document/$documentId': typeof DocumentDocumentIdRoute
  '/lab/embedding': typeof LabEmbeddingRoute
  '/recent/documents': typeof RecentDocumentsRoute
  '/recent/sentences': typeof RecentSentencesRoute
  '/recent/words': typeof RecentWordsRoute
  '/relation/new': typeof RelationNewRoute
  '/sentence/$sentenceId': typeof SentenceSentenceIdRoute
  '/word/$word': typeof WordWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/qna'
    | '/settings'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/new'
    | '/sentence/$sentenceId'
    | '/word/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/qna'
    | '/settings'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/new'
    | '/sentence/$sentenceId'
    | '/word/$word'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/qna'
    | '/settings'
    | '/document/$documentId'
    | '/lab/embedding'
    | '/recent/documents'
    | '/recent/sentences'
    | '/recent/words'
    | '/relation/new'
    | '/sentence/$sentenceId'
    | '/word/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  QnaRoute: typeof QnaRoute
  SettingsRoute: typeof SettingsRoute
  DocumentDocumentIdRoute: typeof DocumentDocumentIdRoute
  LabEmbeddingRoute: typeof LabEmbeddingRoute
  RecentDocumentsRoute: typeof RecentDocumentsRoute
  RecentSentencesRoute: typeof RecentSentencesRoute
  RecentWordsRoute: typeof RecentWordsRoute
  RelationNewRoute: typeof RelationNewRoute
  SentenceSentenceIdRoute: typeof SentenceSentenceIdRoute
  WordWordRoute: typeof WordWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qna': {
      id: '/qna'
      path: '/qna'
      fullPath: '/qna'
      preLoaderRoute: typeof QnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$documentId': {
      id: '/document/$documentId'
      path: '/document/$documentId'
      fullPath: '/document/$documentId'
      preLoaderRoute: typeof DocumentDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/embedding': {
      id: '/lab/embedding'
      path: '/lab/embedding'
      fullPath: '/lab/embedding'
      preLoaderRoute: typeof LabEmbeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/documents': {
      id: '/recent/documents'
      path: '/recent/documents'
      fullPath: '/recent/documents'
      preLoaderRoute: typeof RecentDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/sentences': {
      id: '/recent/sentences'
      path: '/recent/sentences'
      fullPath: '/recent/sentences'
      preLoaderRoute: typeof RecentSentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/words': {
      id: '/recent/words'
      path: '/recent/words'
      fullPath: '/recent/words'
      preLoaderRoute: typeof RecentWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relation/new': {
      id: '/relation/new'
      path: '/relation/new'
      fullPath: '/relation/new'
      preLoaderRoute: typeof RelationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentence/$sentenceId': {
      id: '/sentence/$sentenceId'
      path: '/sentence/$sentenceId'
      fullPath: '/sentence/$sentenceId'
      preLoaderRoute: typeof SentenceSentenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word/$word': {
      id: '/word/$word'
      path: '/word/$word'
      fullPath: '/word/$word'
      preLoaderRoute: typeof WordWordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  QnaRoute: QnaRoute,
  SettingsRoute: SettingsRoute,
  DocumentDocumentIdRoute: DocumentDocumentIdRoute,
  LabEmbeddingRoute: LabEmbeddingRoute,
  RecentDocumentsRoute: RecentDocumentsRoute,
  RecentSentencesRoute: RecentSentencesRoute,
  RecentWordsRoute: RecentWordsRoute,
  RelationNewRoute: RelationNewRoute,
  SentenceSentenceIdRoute: SentenceSentenceIdRoute,
  WordWordRoute: WordWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
